/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCopying.h"
#import "assistantd-Structs.h"
#import "NSMutableCopying.h"
#import "NSObject.h"


@protocol AceObject <NSObject, NSCopying, NSMutableCopying>
- (id)mutableCopyWithZone:(NSZone*)zone;
- (id)copyWithZone:(NSZone*)zone;
- (id)groupIdentifier;
- (id)encodedClassName;
- (id)properties;
- (id)dictionary;
- (id)initWithDictionary:(id)dictionary context:(id)context;
- (id)initWithDictionary:(id)dictionary;
- (id)init;
@end

