/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary;

__attribute__((visibility("hidden")))
@interface ADAceManagedObject : XXUnknownSuperclass {
}
@property(retain, nonatomic) NSString* oldId;
@property(retain, nonatomic) NSString* aceKey;
@property(retain, nonatomic) NSDictionary* aceDictionary;
@end

