/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSStreamDelegate.h"
#import "assistantd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSOutputStream, ADBufferedOutputStream, NSInputStream, ADAceOutputStream, ADAceInputData, NSString, NSURL, NSThread, NSConditionLock, NSTimer;
@protocol ADAceConnectionDelegate;

__attribute__((visibility("hidden")))
@interface ADAceConnection : XXUnknownSuperclass <NSStreamDelegate> {
	id<ADAceConnectionDelegate> _delegate;
	NSOutputStream* _httpOutputStream;
	NSInputStream* _httpInputStream;
	CFHTTPMessageRef _httpResponseHeader;
	ADBufferedOutputStream* _bufferedOutputStream;
	ADAceOutputStream* _output;
	ADAceInputData* _input;
	NSURL* _url;
	NSString* _aceHost;
	BOOL _connected;
	BOOL _opened;
	NSThread* _thread;
	NSConditionLock* _runningLock;
	int _retries;
	NSTimer* _timeoutTimer;
	double _timeoutValue;
	NSTimer* _keepAliveTimer;
	double _lastActivityTimestamp;
	int _interfaceIndex;
	unsigned long _pingIndex;
	CFDictionaryRef _outstandingPongs;
	BOOL _didAnalyzeThisRequest;
}
@property(assign, nonatomic) id<ADAceConnectionDelegate> delegate;
- (void)_safeFinishRequestCleanly;
- (void)_safeScheduleKeepAliveTimer;
- (void)stream:(id)stream handleEvent:(unsigned)event;
- (BOOL)_shouldRetryForError:(id)error;
- (void)_handleData:(id)data;
- (void)_handleHeader:(id)header;
- (void)_terminateConnectionClearingDelegate:(BOOL)delegate;
- (void)_connectionDidOpen;
- (void)_finishRequestCleanly;
- (void)_startConnectionWithAceHost:(id)aceHost;
- (void)_startRunLoop;
- (unsigned)_interfaceIndexForStream:(id)stream;
- (void)_scheduleKeepAliveTimer;
- (void)_sendKeepAlivePacket;
- (void)_analyzeCurrentConnection;
- (void)_scheduleTimeout;
- (void)_safeTimeoutFired;
- (void)_cancelTimeout;
- (unsigned)interfaceIndex;
- (void)startWithAceHost:(id)aceHost timeout:(double)timeout;
- (void)close;
- (void)setSendKeepAlive:(BOOL)alive;
- (BOOL)sendCommand:(id)command error:(id*)error;
- (void)dealloc;
- (id)initWithURL:(id)url;
@end

