/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistantd-Structs.h"

@class ADBufferedOutputStream;

__attribute__((visibility("hidden")))
@interface ADAceOutputStream : XXUnknownSuperclass {
	ADBufferedOutputStream* _output;
	BOOL _compressed;
	z_stream_s _z;
	unsigned char _zbuffer[8192];
}
- (void)dealloc;
- (BOOL)finish:(id*)finish;
- (BOOL)writeObject:(id)object format:(unsigned)format error:(id*)error;
- (BOOL)writeObject:(id)object error:(id*)error;
- (BOOL)_writeHeader:(id*)header;
- (BOOL)writePong:(unsigned)pong error:(id*)error;
- (BOOL)writePing:(unsigned)ping error:(id*)error;
- (BOOL)writeNopWithError:(id*)error;
- (BOOL)_write:(id)write compress:(BOOL)compress flushMode:(int)mode error:(id*)error;
- (BOOL)_write:(const void*)write length:(unsigned)length compress:(BOOL)compress flushMode:(int)mode error:(id*)error;
- (id)initWithBufferedOutputStream:(id)bufferedOutputStream compressed:(BOOL)compressed error:(id*)error;
@end

