/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ADAceConnectionDelegate
- (void)aceConnection:(id)connection didEncounterError:(id)error;
- (void)aceConnectionDidClose:(id)aceConnection;
- (void)aceConnection:(id)connection didReceiveAceObject:(id)object;
- (void)aceConnectionDidOpen:(id)aceConnection;
@end

