/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSError;

__attribute__((visibility("hidden")))
@interface ADAceNetworkAnalyzer : XXUnknownSuperclass {
	BOOL _finishedLoading;
	NSError* _failureError;
}
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connectionDidFinishLoading:(id)connection;
- (void)dealloc;
- (void)doNetworkAnalysis:(id)analysis;
- (id)_getResultsForCommand:(const char*)command;
@end

