/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABAssistantManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol ABAssistantManager;

__attribute__((visibility("hidden")))
@interface ADAddressBookManager : XXUnknownSuperclass <ABAssistantManagerDelegate> {
	id<ABAssistantManager> _abAssistantManager;
}
- (void)meCardChanged;
- (void)unregisterForMeCardNotifications;
- (void)registerForMeCardNotifications;
- (id)sources;
- (id)meCards;
- (id)_abAssistantManager;
- (void)prepare;
- (void)dealloc;
@end

