/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistantd-Structs.h"

@class NSData;

__attribute__((visibility("hidden")))
@interface ADAuthenticator : XXUnknownSuperclass {
	int _state;
	dispatch_queue_s* _queue;
	NACContextOpaque_Ref _nacContext;
	NSData* _requestData;
	NSData* _sessionInfo;
	double _duration;
}
@property(retain, nonatomic, setter=_setSessionInfo:) NSData* _sessionInfo;
@property(retain, nonatomic, setter=_setRequestData:) NSData* _requestData;
- (void)reset;
- (double)sessionInfoDuration;
- (id)signedDataForData:(id)data;
- (void)setSessionInfo:(id)info duration:(double)duration;
- (id)requestData;
- (void)prepareWithCertificateData:(id)certificateData completion:(id)completion;
- (int)state;
- (void)_setNACContext:(NACContextOpaque_Ref)context;
- (long)_signData:(id)data withSessionInfo:(id)sessionInfo signedData:(id*)data3;
- (void)_getSessionRequestForCertificate:(id)certificate completion:(id)completion;
- (void)dealloc;
- (id)initWithTargetQueue:(dispatch_queue_s*)targetQueue;
@end

