/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistantd-Structs.h"

@class NSMutableData, NSOutputStream;

__attribute__((visibility("hidden")))
@interface ADBufferedOutputStream : XXUnknownSuperclass {
	dispatch_queue_s* _outputQueue;
	NSOutputStream* _outputStream;
	NSMutableData* _outputData;
	unsigned _outputDataPosition;
}
- (void)close;
- (void)sendData:(id)data;
- (void)tryToWrite;
- (void)_tryToWriteData:(id)writeData;
- (void)dealloc;
- (id)initWithOutputStream:(id)outputStream;
@end

