/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ADCallObserver : XXUnknownSuperclass {
	BOOL _isObserving;
	id _stateChangedBlock;
}
@property(copy, nonatomic, setter=_setStateChangedBlock:) id _stateChangedBlock;
- (void)stopObservingCallState;
- (void)startObservingCallStateWithBlock:(id)block;
- (void)_callStateChanged:(int)changed;
- (void)dealloc;
@end

