/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, SARequestCompleted, SABaseCommand;

__attribute__((visibility("hidden")))
@interface ADCommandResultsManager : XXUnknownSuperclass {
	SARequestCompleted* _requestCompleted;
	NSArray* _callbacks;
	int _callbacksIndex;
	SABaseCommand* _commandAwaitingReply;
}
@property(retain, nonatomic, setter=_setCommandAwatingReply:) SABaseCommand* _commandAwaitingReply;
@property(retain, nonatomic, setter=_setCallbacks:) NSArray* _callbacks;
@property(retain, nonatomic, setter=_setRequestCompleted:) SARequestCompleted* _requestCompleted;
- (BOOL)callbacksContainCallCommand;
- (BOOL)_callbacks:(id)callbacks containsCommandClass:(Class)aClass;
- (id)commandsToPreheat;
- (id)nextCommandsForReply:(id)reply;
- (void)startNewCallbackContext:(id)context;
- (void)reset;
- (BOOL)hasCallbackContext;
- (void)dealloc;
@end

