/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "assistantd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "BBObserverDelegate.h"

@class BBObserver, NSArray, NSMutableDictionary;
@protocol ADContextManagerDelegate;

__attribute__((visibility("hidden")))
@interface ADContextManager : XXUnknownSuperclass <BBObserverDelegate> {
	dispatch_queue_s* _queue;
	id<ADContextManagerDelegate> _delegate;
	BBObserver* _observer;
	NSArray* _latestAppContext;
	NSMutableDictionary* _bulletins;
	BOOL _isLocked;
}
@property(copy, nonatomic) NSArray* latestAppContext;
@property(assign, nonatomic) id<ADContextManagerDelegate> delegate;
- (void)observer:(id)observer removeBulletin:(id)bulletin;
- (void)observer:(id)observer modifyBulletin:(id)bulletin;
- (void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
- (void)markBulletinAsAcknolwedgedForDomainObject:(id)domainObject;
- (void)getAlertContext:(id)context;
- (void)getAppContext:(id)context;
- (id)_alertContextFromBulletins:(id)bulletins;
- (void)setLockState:(BOOL)state;
- (void)dealloc;
- (id)initWithDelegate:(id)delegate;
- (id)init;
@end

