/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ADCommandCenterSpeechDelegate <NSObject>
- (void)adSpeechSetRecordingRoute:(int)route;
- (int)adSpeechRecordingRoute;
- (void)adSpeechRecognitionDidFail:(id)adSpeechRecognition;
- (void)adSpeechDidRecognizePhrases:(id)adSpeech correctionContext:(id)context;
- (void)adSpeechRecordingDidFail:(id)adSpeechRecording;
- (void)adSpeechRecordingDidCancel;
- (void)adSpeechRecordingDidEnd;
- (void)adSpeechRecordingDidUpdateAveragePower:(float)adSpeechRecording peakPower:(float)power;
- (void)adSpeechRecordingDidBegin;
- (void)adSpeechRecordingWillBegin;
@end

