/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "assistantd-Structs.h"
#import "ADDaemon.h"
#import <Foundation/NSDateFormatter.h>

@class DKServer;

__attribute__((visibility("hidden")))
@interface ADDaemon : NSDateFormatter {
	dispatch_queue_s* _queue;
	DKServer* _clientServer;
	DKServer* _dictationServer;
	DKServer* _settingsServer;
	xpc_connection_s* _syncListener;
	dispatch_source_s* _idleTimerSource;
	BOOL _idleTimerFlag;
	BOOL _syncNotifyTokenRegistered;
	int _syncNotifyToken;
}
+ (id)sharedDaemon;
- (void)scheduleValidationRefreshForInterval:(double)interval;
- (void)scheduleDestroyJobForAccount:(id)account;
- (void)scheduleSyncJob;
- (void)_daemonWillShutdown;
- (void)_daemonDidLaunch;
- (void)_registerForSyncNotifications;
- (void)_setupSyncListener;
- (void)_setupBackgroundTaskAgent;
- (id)_settingsServer;
- (void)_setupSettingsServer;
- (id)_dictationServer;
- (void)_setupDictationServer;
- (id)_clientServer;
- (void)_setupClientServer;
- (void)_setupIdleTimer;
- (void)_resetIdleTimerFlag;
- (BOOL)_idleTimerConditionsMet;
- (dispatch_queue_s*)_queue;
- (void)keepAlive;
- (void)shutdown;
- (void)run;
- (void)dealloc;
- (id)init;
@end

@interface ADDaemon (Public)
- (void)_registerSettingsPublicHandlers;
- (void)_registerDictationPublicHandlers;
- (void)_registerClientPublicHandlers;
@end

@interface ADDaemon (Private)
- (void)_registerClientPrivateHandlers;
@end

