/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "assistantd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ADHandsFreeManager : XXUnknownSuperclass {
	CFSetRef _observers;
}
+ (id)sharedManager;
- (void)removeHandsFreeStateObserver:(id)observer;
- (void)addHandsFreeStateObserver:(id)observer;
- (void)_stopListeningForAudioRouteChanges;
- (void)_listenForAudioRouteChanges;
- (void)_notifyObservers:(CFBooleanRef)observers;
- (void)dealloc;
- (id)init;
@end

