/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSEntityDescription, NSFetchRequest, NSManagedObjectContext;

__attribute__((visibility("hidden")))
@interface ADManagedStore : XXUnknownSuperclass {
	NSManagedObjectContext* _moc;
	NSEntityDescription* _aceEntityDesc;
	NSFetchRequest* _fetchRequest;
}
@property(readonly, assign, nonatomic) NSEntityDescription* _aceEntityDesc;
@property(readonly, assign, nonatomic) NSManagedObjectContext* _moc;
+ (id)_sharedPersistentStoreCoordinator;
+ (id)_aceMOM;
- (void)save;
- (void)setUndoManager:(id)manager;
- (id)_allObjects;
- (void)removeAllObjects;
- (id)oldIdForKey:(id)key;
- (void)setDomainObject:(id)object forKey:(id)key;
- (void)setDomainObject:(id)object oldId:(id)anId forKey:(id)key;
- (id)domainObjectForKey:(id)key;
- (id)_managedObjectForKey:(id)key;
- (void)dealloc;
- (id)init;
@end

