/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistantd-Structs.h"

@protocol ADNetworkManagerDelegate;

__attribute__((visibility("hidden")))
@interface ADNetworkManager : XXUnknownSuperclass {
	id<ADNetworkManagerDelegate> _delegate;
	SCNetworkReachabilityRef _scReachability;
	unsigned _flags;
}
@property(assign, nonatomic) id<ADNetworkManagerDelegate> delegate;
- (unsigned)WWANInterfaceIndex;
- (void)stopMonitoringNetwork;
- (void)startMonitoringNetworkForHost:(id)host onQueue:(dispatch_queue_s*)queue;
- (void)_setFlags:(unsigned)flags;
- (void)dealloc;
@end

