/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ADRetryManager : XXUnknownSuperclass {
	int _retryCount;
	NSMutableArray* _requestCommands;
	BOOL _needsToRetryNakedCommands;
	NSMutableArray* _nakedCommands;
}
- (void)clearNakedCommands;
- (id)nakedCommandsToRetry;
- (void)setNeedsToRetryNakedCommands;
- (id)retryRequestId;
- (id)originalRequestId;
- (BOOL)commandRefsRestartCommand:(id)command;
- (id)commandsToRetry;
- (void)setLastReceivedCommand:(id)command;
- (void)endRetryableRequestForCommand:(id)command;
- (BOOL)shouldRetryOnConnectionFailure;
- (void)appendCommandToRequest:(id)request;
- (void)beginRetryableRequest:(id)request;
- (BOOL)_commandRefsOrIsCurrentRequest:(id)request;
- (void)_clearRequestCommands;
- (void)dealloc;
@end

