/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "assistantd-Structs.h"
#import "ADAceConnectionDelegate.h"
#import "ADNetworkManagerDelegate.h"
#import "MCProfileConnectionObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, ADAddressBookManager, NSString, NSMutableArray, ADAuthenticator, ADNetworkManager, ADAccount, ADAceConnection;
@protocol ADSessionDelegate;

__attribute__((visibility("hidden")))
@interface ADSession : XXUnknownSuperclass <ADAceConnectionDelegate, ADNetworkManagerDelegate, MCProfileConnectionObserver> {
	dispatch_queue_s* _queue;
	ADAccount* _account;
	NSMutableArray* _pendingCommands;
	NSMutableSet* _limboIds;
	ADAceConnection* _serverConnection;
	int _state;
	NSString* _sessionInitCommandId;
	CFDictionaryRef _commandMap;
	NSString* _pendingAssistantDataAnchor;
	double _retryStartTime;
	ADAuthenticator* _authenticator;
	ADNetworkManager* _networkManager;
	dispatch_source_s* _sessionLoadTimerSource;
	id<ADSessionDelegate> _delegate;
	BOOL _shouldSendAssistantData;
	BOOL _isRegisteredForSADNotifications;
	ADAddressBookManager* _addressBookManager;
	NSMutableArray* _cachedRestrictions;
	unsigned _ioConnect;
	IONotificationPortRef _ioNotificationPortRef;
	unsigned _ioNotifier;
	BOOL _usingCachedCertificateData;
	BOOL _usingCachedValidationData;
	BOOL _hasActiveRequest;
	BOOL _checkForWiFiTransitionOnRequestEnd;
}
@property(copy, nonatomic, setter=_setPendingAssistantDataAnchor:) NSString* _pendingAssistantDataAnchor;
@property(copy, nonatomic, setter=_setSessionInitCommandId:) NSString* _sessionInitCommandId;
@property(readonly, assign, nonatomic) dispatch_queue_s* _queue;
@property(readonly, assign, nonatomic) ADAccount* _account;
@property(assign, nonatomic) id<ADSessionDelegate> delegate;
- (void)setHasActiveRequest:(BOOL)request;
- (void)cancel;
- (void)handleCommand:(id)command;
- (void)sendCommand:(id)command;
- (void)refreshValidationData;
- (void)beginUpdatingAssistantData;
- (void)preheat;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)profileConnection userInfo:(id)info;
- (void)_locationRestrictionChanged:(id)changed;
- (void)_languageCodeChanged:(id)changed;
- (void)_meCardChanged:(id)changed;
- (void)_localeChanged:(id)changed;
- (void)_systemTimeZoneChanged:(id)changed;
- (void)_recheckForWiFiTransition;
- (void)networkManagerLostNonWWANConnectivity:(id)connectivity;
- (void)networkManagerNonWWANDidBecomeAvailable:(id)networkManagerNonWWAN;
- (void)aceConnection:(id)connection didEncounterError:(id)error;
- (void)aceConnectionDidClose:(id)aceConnection;
- (void)aceConnection:(id)connection didReceiveAceObject:(id)object;
- (void)aceConnectionDidOpen:(id)aceConnection;
- (void)_startConnection;
- (void)_eagerAuthDidComplete;
- (void)_connectionOpened;
- (void)_startSession;
- (void)_continueAuthentication;
- (void)_continueAuthWithCertificateData:(id)certificateData;
- (void)_continueSessionInitWithValidationData:(id)validationData;
- (void)_authenticationFailed;
- (void)_handleAceObject:(id)object;
- (void)_saPing:(id)ping;
- (void)_saCommandFailed:(id)failed;
- (void)_assistantFailedForReason:(id)reason;
- (void)_saGetAssistantData:(id)data;
- (void)_saSetConnectionHeader:(id)header;
- (void)_saAssistantNotFound:(id)found;
- (void)_saAssistantLoaded:(id)loaded;
- (void)_saAssistantCreated:(id)created;
- (void)_saCreateSessionInfoResponse:(id)response;
- (void)_saGetSessionCertificateResponse:(id)response;
- (void)_saSessionValidationFailed:(id)failed;
- (void)_sendAssistantDataChangedSinceAnchor:(id)anchor refId:(id)anId;
- (id)_generatedAnchorFromSetAssistantData:(id)setAssistantData;
- (void)_sendCommandFailedWithRefId:(id)refId;
- (void)_sendCreateAssistantWithValidationData:(id)validationData;
- (void)_sendLoadAssistantWithId:(id)anId speechId:(id)anId2 validationData:(id)data;
- (void)_sendCreateSessionInfoRequestWithData:(id)data;
- (void)_sendGetSessionCertificateData;
- (void)_scheduleSessionLoadTimeout;
- (void)_cancelSessionLoadTimeout;
- (void)_informDelegateOfError:(id)error;
- (void)_passObjectToDelegate:(id)delegate;
- (void)_clearLimbo;
- (void)_sendLimboCommand:(id)command;
- (void)_sendPendingCommands;
- (void)_addPendingCommand:(id)command;
- (BOOL)_refIdIsLimboId:(id)anId;
- (void)_removeLimboId:(id)anId;
- (void)_addLimboId:(id)anId;
- (id)_pendingCommands;
- (BOOL)_sendServerCommand:(id)command;
- (BOOL)_shouldSendAssistantData;
- (void)_unregisterForAssistantDataNotifications;
- (void)_registerForAssistantDataNotifications;
- (void)_unregisterForSleepNotification;
- (void)_registerForSleepNotification;
- (void)_powerChangedMessageType:(unsigned)type notificationID:(long)anId;
- (void)_invalidateABManager;
- (void)_eagerlyLoadAddressBookManager;
- (id)_addressBookManager;
- (void)_clearRestrictionsCache;
- (id)_restrictions;
- (void)_setCachedValidationData:(id)data withDuration:(double)duration;
- (id)_cachedValidationData;
- (void)_setCachedServerCertificate:(id)certificate;
- (id)_cachedServerCertificate;
- (id)_authenticator;
- (BOOL)_authenticationDisabled;
- (BOOL)_isSessionActive;
- (void)_resetServerConnection;
- (id)_serverConnection;
- (void)dealloc;
- (id)initOnQueue:(dispatch_queue_s*)queue withAccount:(id)account;
@end

