/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ADSessionDelegate <NSObject>
- (void)assistantSessionConnectionDidReset:(id)assistantSessionConnection;
- (BOOL)assistantSessionShouldRestartConnectionOnWiFi:(id)assistantSession;
- (void)assistantSession:(id)session receivedError:(id)error;
- (void)assistantSession:(id)session receivedCommand:(id)command;
@end

