/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistantd-Structs.h"

@class ADServiceStatistics, NSString, DKConnection, NSDictionary;
@protocol ADServiceConnectionSyncDelegate;

__attribute__((visibility("hidden")))
@interface ADServiceConnection : XXUnknownSuperclass {
	dispatch_queue_s* _targetQueue;
	NSString* _identifier;
	NSString* _path;
	DKConnection* _connection;
	BOOL _serviceLoaded;
	ADServiceStatistics* _stats;
	NSDictionary* _commandMap;
	NSDictionary* _anchorKeyClassMap;
	NSString* _domainObjectClearingClassName;
	BOOL _preheated;
	id<ADServiceConnectionSyncDelegate> _syncDelegate;
}
@property(assign, nonatomic) id<ADServiceConnectionSyncDelegate> syncDelegate;
@property(readonly, assign, nonatomic) NSString* identifier;
- (void)preheatServiceBundle;
- (void)sendClearDomainObjects;
- (void)sendBeginSyncWithAnchor:(id)anchor validity:(id)validity forKey:(id)key;
- (void)_handleSyncMessage:(id)message;
- (id)_syncClassForAnchorKey:(id)anchorKey;
- (void)sendClientBoundCommand:(id)command domain:(id)domain reply:(id)reply;
- (id)_bundleClassForDomain:(id)domain commandName:(id)name;
- (void)_handleOpenURLMessage:(id)message;
- (void)_handleCommandMessage:(id)message;
- (void)_handleDisconnect;
- (void)_handleMessage:(id)message;
- (void)dealloc;
- (id)initWithIdentifier:(id)identifier path:(id)path commandMap:(id)map anchorMap:(id)map4 clearingClass:(id)aClass queue:(dispatch_queue_s*)queue;
@end

