/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADServiceConnectionSyncDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class ADServiceConnection, SASyncAnchor, ADAccount, NSString, ADServiceManager, NSMutableArray;
@protocol ADSyncManagerDelegate;

__attribute__((visibility("hidden")))
@interface ADSyncManager : XXUnknownSuperclass <ADServiceConnectionSyncDelegate> {
	ADAccount* _account;
	ADServiceManager* _serviceManager;
	NSString* _anchorsRequestId;
	NSMutableArray* _anchorsToSync;
	NSMutableArray* _syncedAnchors;
	SASyncAnchor* _currentAnchor;
	ADServiceConnection* _currentSyncConnection;
	id<ADSyncManagerDelegate> _delegate;
	id _continueBlock;
	BOOL _currentSyncShouldCancel;
	BOOL _syncNeededOverride;
	BOOL _forceResetOnNextSync;
}
@property(copy, nonatomic, setter=_setContinueBlock:) id _continueBlock;
@property(retain, nonatomic, setter=_setCurrentSyncConnection:) ADServiceConnection* _currentSyncConnection;
@property(retain, nonatomic, setter=_setCurrentAnchor:) SASyncAnchor* _currentAnchor;
@property(assign, setter=_setForceResetOnNextSync:) BOOL _forceResetOnNextSync;
@property(copy, nonatomic) NSString* anchorsRequestId;
- (void)syncFinishedOnConnection:(id)connection;
- (void)connection:(id)connection receivedChunkWithPreAnchor:(id)preAnchor post:(id)post anchorValidity:(id)validity toAdd:(id)add toRemove:(id)remove continueBlock:(id)block;
- (void)setSyncNeeded;
- (void)cancelSyncForAnchor:(id)anchor;
- (void)continueSync;
- (BOOL)isSyncing;
- (void)prepareSyncWithAnchors:(id)anchors delegate:(id)delegate;
- (id)anchorKeysNeedingSync;
- (id)_sortedAnchorsFromAnchors:(id)anchors;
- (id)_preferredSyncKeyOrder;
- (BOOL)_needsSync;
- (void)_postSyncFinishedNotification;
- (void)_currentAnchorFinishedWithSuccess:(BOOL)success;
- (void)_continueSync;
- (void)_setCurrentAnchorToNext;
- (void)_finishSync;
- (id)_connectionForAnchorKey:(id)anchorKey;
- (void)_setAnchorsToSync:(id)sync;
- (void)dealloc;
- (id)initWithAccount:(id)account serviceManager:(id)manager;
@end

