/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSUndoManager, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ADUndoManager : XXUnknownSuperclass {
	NSUndoManager* _undoMan;
	NSMutableArray* _undoGroupRequests;
	NSMutableArray* _redoGroupRequests;
}
- (void)clearUndoStack;
- (void)redo;
- (void)undo;
- (void)endUndoGrouping;
- (id)prepareInvocationWithTarget:(id)target;
- (void)beginUndoGroupingForRequest:(id)request;
- (id)underlyingUndoManager;
- (void)dealloc;
- (id)init;
@end

