/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct CGSize {
	float _field1;
	float _field2;
} CGSize;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct _xpc_connection_s xpc_connection_s;

typedef struct dispatch_source_s dispatch_source_s;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFHTTPMessage* CFHTTPMessageRef;

typedef struct internal_state internal_state;

typedef struct z_stream_s {
	char* next_in;
	unsigned avail_in;
	unsigned total_in;
	char* next_out;
	unsigned avail_out;
	unsigned total_out;
	char* msg;
	internal_state* state;
	/*function-pointer*/ void* zalloc;
	/*function-pointer*/ void* zfree;
	void* opaque;
	int data_type;
	unsigned adler;
	unsigned reserved;
} z_stream_s;

typedef struct ADAceParsedPacket {
	int _field1;
	union {
		unsigned _field1;
		unsigned _field2;
		id _field3;
	} _field2;
} ADAceParsedPacket;

typedef struct IONotificationPort* IONotificationPortRef;

typedef struct __CFSet* CFSetRef;

typedef struct __CFBoolean* CFBooleanRef;

typedef struct NACContextOpaque_* NACContextOpaque_Ref;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;


