/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SAAceSerializable.h"

@class NSString;

@protocol SAAceCommand <SAAceSerializable>
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSString* aceId;
@end

