/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ADSADOCommand.h"
#import "ADCommandCenterClient.h"
#import "ADCommandCenterRequestDelegate.h"
#import "ADCommandCenterSpeechDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (AFDaemonMessaging)
- (void)setInfoWithAceObject:(id)aceObject;
@end

@interface XXUnknownSuperclass (AssistantExtensions)
+ (id)hexStringFromBytes:(const char*)bytes length:(unsigned)length;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (SADExtras) <ADSADOCommand>
- (id)expectedResponseClassName;
- (id)domainFromSADObject;
@end

@interface XXUnknownSuperclass (Assistant) <ADCommandCenterClient, ADCommandCenterRequestDelegate, ADCommandCenterSpeechDelegate>
- (void)adSpeechSetRecordingRoute:(int)route;
- (int)adSpeechRecordingRoute;
- (void)adSpeechRecognitionDidFail:(id)adSpeechRecognition;
- (void)adSpeechDidRecognizePhrases:(id)adSpeech correctionContext:(id)context;
- (void)adSpeechRecordingDidFail:(id)adSpeechRecording;
- (void)adSpeechRecordingDidCancel;
- (void)adSpeechRecordingDidEnd;
- (void)adSpeechRecordingDidUpdateAveragePower:(float)adSpeechRecording peakPower:(float)power;
- (void)adSpeechRecordingDidBegin;
- (void)adSpeechRecordingWillBegin;
- (void)adShouldSpeakChanged:(BOOL)ad;
- (void)adRequestDidFailWithError:(id)adRequest;
- (void)adRequestReplyContextMayInitiateCall;
- (void)adRequestDidReceiveCommand:(id)adRequest;
- (void)adRequestDidFinish;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (BOOL)shouldRetry;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (id)afSpeechTokenPhrases;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (id)description;
- (id)_firstInterpretation;
- (id)afCorrectionContext;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (void)setAFDictationOptions:(id)options;
- (id)_sasReturnKeyTypeFromAFDictationReturnKeyType:(int)afdictationReturnKeyType;
- (id)_sasKeyboardTypeFromAFDicatationKeyboardType:(int)afdicatationKeyboardType;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (void)setAFCorrectionContext:(id)context;
- (void)setAFSpeechCorrectionInfo:(id)info;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (void)setAFCorrectionContext:(id)context;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (void)setAFSpeechActivationEvent:(int)event;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (id)description;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADRetryManager)
- (BOOL)_ad_isRetryableCommand;
@end

@interface XXUnknownSuperclass (ADSAExtensions)
- (int)resultCallbackCode;
@end

@interface XXUnknownSuperclass (ResultCallbacks)
- (int)resultCallbackCode;
@end

@interface XXUnknownSuperclass (ResultCallbacks)
- (int)resultCallbackCode;
@end

@interface XXUnknownSuperclass (ResultCallbacks)
- (int)resultCallbackCode;
@end

@interface XXUnknownSuperclass (AssistantExtensions)
- (BOOL)isOlderThanAge:(id)age;
- (id)age;
- (BOOL)isWithinAccuracy:(double)accuracy;
@end

@interface XXUnknownSuperclass (ADLocationExtensions)
- (void)setPropertiesWithCLLocation:(id)cllocation;
@end

@interface XXUnknownSuperclass (ADLocationExtensions)
- (double)desiredCLAccuracy;
@end

