/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import <Foundation/NSObject.h>
#import "AceObject.h"
#import "SAObjects-Structs.h"
#import "NSMutableCopying.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSMutableDictionary;
@protocol AceContext;

@protocol AceObject <NSObject, NSCopying, NSMutableCopying>
- (id)encodedClassName;
- (id)initWithDictionary:(id)dictionary context:(id)context;
- (id)copyWithZone:(NSZone*)zone;
- (id)init;
- (id)groupIdentifier;
- (id)properties;
- (id)mutableCopyWithZone:(NSZone*)zone;
- (id)initWithDictionary:(id)dictionary;
- (id)dictionary;
@end

@interface AceObject : NSObject <AceObject> {
	NSMutableDictionary* _dict;
	id<AceContext> _context;
}
+ (id)aceObjectWithGenericCommand:(id)genericCommand context:(id)context;
+ (id)_aceObjectWithMutableDictionary:(id)mutableDictionary context:(id)context;
+ (id)aceObjectArrayWithDictionaryArray:(id)dictionaryArray baseClass:(Class)aClass context:(id)context;
+ (id)aceObjectDictionaryWithDictionary:(id)dictionary baseClass:(Class)aClass context:(id)context;
+ (id)aceObjectArrayWithDictionaryArray:(id)dictionaryArray baseProtocol:(id)protocol context:(id)context;
+ (id)aceObjectDictionaryWithDictionary:(id)dictionary baseProtocol:(id)protocol context:(id)context;
+ (id)dictionaryArrayWithAceObjectArray:(id)aceObjectArray;
+ (id)dictionaryWithAceObjectDictionary:(id)aceObjectDictionary;
+ (id)newAceObjectWithGenericCommand:(id)genericCommand context:(id)context;
+ (id)newAceObjectWithDictionary:(id)dictionary context:(id)context;
+ (id)_newAceObjectWithMutableDictionary:(id)mutableDictionary context:(id)context;
+ (id)aceObjectWithDictionary:(id)dictionary context:(id)context;
+ (id)_descriptionOf:(id)of prefix:(id)prefix;
- (void)setProperty:(id)property forKey:(id)key;
- (id)propertyForKey:(id)key;
- (void)setTopLevelProperty:(id)property forKey:(id)key;
- (id)_initWithMutableDictionary:(id)mutableDictionary context:(id)context;
- (id)topLevelPropertyForKey:(id)key;
- (id)encodedClassName;
- (id)initWithDictionary:(id)dictionary context:(id)context;
- (BOOL)isEqual:(id)equal;
- (unsigned)hash;
- (id)description;
- (id)copyWithZone:(NSZone*)zone;
- (id)init;
- (void)dealloc;
- (id)groupIdentifier;
- (id)properties;
- (id)mutableCopyWithZone:(NSZone*)zone;
- (id)initWithDictionary:(id)dictionary;
- (id)context;
- (id)dictionary;
@end

