/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "AceContext.h"
#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface BasicAceContext : NSObject <AceContext> {
	NSMutableDictionary* _groupMap;
	NSMutableDictionary* _objectMap;
}
- (void)addAcronym:(id)acronym forGroup:(id)group;
- (void)addClass:(Class)aClass forCommand:(id)command inGroup:(id)group;
- (id)aceObjectWithDictionary:(id)dictionary;
- (Class)classWithClassName:(id)className group:(id)group;
- (id)init;
- (void)dealloc;
@end

