/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAPhone.h"


@interface SAABPhone : SAPhone {
}
+ (id)phoneWithDictionary:(id)dictionary context:(id)context;
+ (id)phone;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

