/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class SAEmail, NSURL, SALocation, NSString, NSDate, SAPhone, NSNumber;

@interface SAABPersonSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* scope;
@property(copy, nonatomic) NSString* relationship;
@property(retain, nonatomic) SAPhone* phone;
@property(copy, nonatomic) NSString* name;
@property(retain, nonatomic) NSNumber* me;
@property(retain, nonatomic) SAEmail* email;
@property(copy, nonatomic) NSString* company;
@property(copy, nonatomic) NSDate* birthday;
@property(retain, nonatomic) SALocation* address;
@property(copy, nonatomic) NSURL* accountIdentifier;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)personSearch;
+ (id)personSearchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

