/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADeferredKeyObject.h"
#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSNumber;

@interface SAAceView : AceObject <SAAceSerializable, SADeferredKeyObject> {
}
@property(copy, nonatomic) NSString* viewId;
@property(copy, nonatomic) NSString* speakableText;
@property(retain, nonatomic) NSNumber* listenAfterSpeaking;
+ (id)aceView;
+ (id)aceViewWithDictionary:(id)dictionary context:(id)context;
- (id)deferredKeys;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

