/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSNumber, NSString, NSArray;

@interface SAAlarmObject : SADomainObject {
}
@property(retain, nonatomic) NSNumber* relativeOffsetMinutes;
@property(retain, nonatomic) NSNumber* minute;
@property(copy, nonatomic) NSString* label;
@property(retain, nonatomic) NSNumber* hour;
@property(copy, nonatomic) NSArray* frequency;
@property(retain, nonatomic) NSNumber* enabled;
+ (id)objectWithDictionary:(id)dictionary context:(id)context;
+ (id)object;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

