/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray, NSURL, NSString, NSNumber;

@interface SAAlarmSearch : SABaseClientBoundCommand {
}
@property(retain, nonatomic) NSNumber* minute;
@property(copy, nonatomic) NSString* label;
@property(copy, nonatomic) NSURL* identifier;
@property(retain, nonatomic) NSNumber* hour;
@property(copy, nonatomic) NSArray* frequency;
@property(retain, nonatomic) NSNumber* enabled;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

