/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSArray, NSString;

@interface SAAlarmSearchCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSArray* results;
+ (id)searchCompletedWithResults:(id)results;
+ (id)searchCompleted;
+ (id)searchCompletedWithDictionary:(id)dictionary context:(id)context;
- (id)initWithResults:(id)results;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

