/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSURL, NSString;

@interface SAAnswerObjectLine : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSString* text;
@property(copy, nonatomic) NSURL* image;
+ (id)objectLine;
+ (id)objectLineWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

