/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray, NSURL, NSString, NSDate, NSNumber;

@interface SACalendarEventSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* timeZoneId;
@property(copy, nonatomic) NSDate* startDate;
@property(copy, nonatomic) NSArray* participants;
@property(copy, nonatomic) NSString* notes;
@property(copy, nonatomic) NSString* location;
@property(retain, nonatomic) NSNumber* limit;
@property(copy, nonatomic) NSURL* eventId;
@property(copy, nonatomic) NSDate* endDate;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)eventSearch;
+ (id)eventSearchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

