/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSArray, NSURL, NSString, NSDate, NSNumber;

@interface SACalendarEvent : SADomainObject {
}
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* timeZoneId;
@property(copy, nonatomic) NSDate* startDate;
@property(copy, nonatomic) NSArray* recurrences;
@property(retain, nonatomic) NSNumber* readOnly;
@property(copy, nonatomic) NSArray* participants;
@property(copy, nonatomic) NSString* notes;
@property(copy, nonatomic) NSString* location;
@property(retain, nonatomic) NSNumber* includeRecurrences;
@property(copy, nonatomic) NSDate* endDate;
@property(copy, nonatomic) NSURL* calendarId;
@property(copy, nonatomic) NSArray* attendees;
@property(assign, nonatomic) BOOL allDay;
@property(copy, nonatomic) NSArray* alerts;
+ (id)eventWithDictionary:(id)dictionary context:(id)context;
+ (id)event;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

