/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSNumber, NSString;

@interface SAClockObject : SADomainObject {
}
@property(copy, nonatomic) NSString* unlocalizedCountryName;
@property(copy, nonatomic) NSString* unlocalizedCityName;
@property(copy, nonatomic) NSString* timezoneId;
@property(copy, nonatomic) NSString* countryName;
@property(copy, nonatomic) NSString* countryCode;
@property(copy, nonatomic) NSString* cityName;
@property(retain, nonatomic) NSNumber* alCityId;
+ (id)objectWithDictionary:(id)dictionary context:(id)context;
+ (id)object;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

