/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, SAClockObject;

@interface SAClockAdd : SABaseClientBoundCommand {
}
@property(retain, nonatomic) SAClockObject* clockToAdd;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)add;
+ (id)addWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

