/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, NSNumber, NSString;

@interface SAClockSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* unlocalizedCountryName;
@property(copy, nonatomic) NSString* unlocalizedCityName;
@property(copy, nonatomic) NSURL* identifier;
@property(copy, nonatomic) NSString* countryCode;
@property(retain, nonatomic) NSNumber* alCityId;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

