/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SAClientBoundCommand.h"
#import "SABaseCommand.h"

@class NSString, NSArray;

@interface SACommandFailed : SABaseCommand <SAServerBoundCommand, SAClientBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSArray* callbacks;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSString* reason;
@property(assign, nonatomic) int errorCode;
+ (id)commandFailed;
+ (id)commandFailedWithDictionary:(id)dictionary context:(id)context;
+ (id)commandFailedWithErrorCode:(int)errorCode;
+ (id)commandFailedWithReason:(id)reason;
- (id)initWithErrorCode:(int)errorCode;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
- (id)initWithReason:(id)reason;
@end

