/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"
#import "SADomainObjectCommand.h"

@class NSArray;

@interface SADomainObjectRetrieve : SABaseClientBoundCommand <SADomainObjectCommand> {
}
@property(copy, nonatomic) NSArray* identifiers;
+ (id)domainObjectRetrieve;
+ (id)domainObjectRetrieveWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

