/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceIdentifiable.h"
#import "AceObject.h"

@class NSURL;

@interface SADomainObject : AceObject <SAAceIdentifiable> {
}
@property(copy, nonatomic) NSURL* identifier;
+ (id)domainObject;
+ (id)domainObjectWithDictionary:(id)dictionary context:(id)context;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

