/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"
#import "SADomainObjectCommand.h"

@class SADomainObject;

@interface SADomainObjectUpdate : SABaseClientBoundCommand <SADomainObjectCommand> {
}
@property(retain, nonatomic) SADomainObject* setFields;
@property(retain, nonatomic) SADomainObject* removeFields;
@property(retain, nonatomic) SADomainObject* identifier;
@property(retain, nonatomic) SADomainObject* addFields;
+ (id)domainObjectUpdate;
+ (id)domainObjectUpdateWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

