/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSDate, NSURL, NSString;

@interface SAEmailSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* toEmail;
@property(copy, nonatomic) NSString* timeZoneId;
@property(copy, nonatomic) NSString* subject;
@property(assign, nonatomic) int status;
@property(copy, nonatomic) NSDate* startDate;
@property(copy, nonatomic) NSString* fromEmail;
@property(copy, nonatomic) NSDate* endDate;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

