/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSNumber;

@interface SAEmail : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSString* label;
@property(retain, nonatomic) NSNumber* favoriteFacetime;
@property(copy, nonatomic) NSString* emailAddress;
+ (id)email;
+ (id)emailWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

