/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAUISnippet.h"

@class NSArray, NSURL, NSString, NSNumber;

@interface SAFmfLocationSnippet : SAUISnippet {
}
@property(copy, nonatomic) NSURL* searchContext;
@property(copy, nonatomic) NSString* proximity;
@property(copy, nonatomic) NSArray* locations;
@property(retain, nonatomic) NSNumber* atRequestedLocation;
+ (id)locationSnippet;
+ (id)locationSnippetWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

