/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SALocation.h"

@class NSNumber, NSString, SAPersonAttribute;

@interface SAFmfLocation : SALocation {
}
@property(retain, nonatomic) NSNumber* locationDate;
@property(retain, nonatomic) SAPersonAttribute* friend;
@property(copy, nonatomic) NSString* emailAddress;
@property(retain, nonatomic) NSNumber* distance;
+ (id)locationWithDictionary:(id)dictionary context:(id)context;
+ (id)location;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

