/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray, NSURL, SALocation, NSString;

@interface SAFmfSearch : SABaseClientBoundCommand {
}
@property(retain, nonatomic) SALocation* requestedLocation;
@property(copy, nonatomic) NSString* proximity;
@property(copy, nonatomic) NSArray* friends;
@property(copy, nonatomic) NSArray* emailAddresses;
@property(retain, nonatomic) SALocation* currentLocation;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

