/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSURL;

@interface SAFmfVisibilityView : SAAceView {
}
@property(assign, nonatomic) BOOL visible;
@property(copy, nonatomic) NSURL* searchContext;
+ (id)visibilityView;
+ (id)visibilityViewWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

