/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"

@class NSString, NSDictionary;

@interface SAGenericCommand : SABaseCommand {
}
@property(readonly, assign, nonatomic, getter=properties) NSDictionary* properties;
@property(readonly, assign, nonatomic) NSString* group;
@property(readonly, assign, nonatomic) NSString* className;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

