/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSNumber, NSString;

@interface SAGetRequestOrigin : SABaseClientBoundCommand {
}
@property(retain, nonatomic) NSNumber* searchTimeout;
@property(retain, nonatomic) NSNumber* maxAge;
@property(copy, nonatomic) NSString* desiredAccuracy;
+ (id)getRequestOrigin;
+ (id)getRequestOriginWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

