/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSString, NSNumber;

@interface SALocation : SADomainObject {
}
@property(copy, nonatomic) NSString* street;
@property(copy, nonatomic) NSString* stateCode;
@property(copy, nonatomic) NSString* postalCode;
@property(retain, nonatomic) NSNumber* longitude;
@property(retain, nonatomic) NSNumber* latitude;
@property(copy, nonatomic) NSString* label;
@property(copy, nonatomic) NSString* countryCode;
@property(copy, nonatomic) NSString* city;
@property(retain, nonatomic) NSNumber* accuracy;
+ (id)locationWithDictionary:(id)dictionary context:(id)context;
+ (id)location;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

