/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString;

@interface SALocalSearchPhoneNumber : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSString* value;
@property(copy, nonatomic) NSString* type;
+ (id)phoneNumberWithDictionary:(id)dictionary context:(id)context;
+ (id)phoneNumber;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

