/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class SALocation, NSString, NSNumber;
@protocol SAAceSerializable;

@interface SALocalSearchMapItem : SADomainObject {
}
@property(retain, nonatomic) NSNumber* placeId;
@property(retain, nonatomic) SALocation* location;
@property(copy, nonatomic) NSString* label;
@property(retain, nonatomic) NSNumber* distanceInMiles;
@property(copy, nonatomic) NSString* detailType;
@property(retain, nonatomic) id<SAAceSerializable> detail;
+ (id)mapItem;
+ (id)mapItemWithDictionary:(id)dictionary context:(id)context;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

