/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class SALocalSearchMapItem, NSURL, NSString, NSNumber;

@interface SALocalSearchShowMapPoints : SABaseClientBoundCommand {
}
@property(assign, nonatomic) BOOL showTraffic;
@property(assign, nonatomic) BOOL showDirections;
@property(retain, nonatomic) NSNumber* regionOfInterestRadiusInMiles;
@property(retain, nonatomic) SALocalSearchMapItem* itemSource;
@property(retain, nonatomic) SALocalSearchMapItem* itemDestination;
@property(copy, nonatomic) NSString* directionsType;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)showMapPoints;
+ (id)showMapPointsWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

