/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString;

@interface SALocalSearchRating : AceObject <SAAceSerializable> {
}
@property(assign, nonatomic) double value;
@property(copy, nonatomic) NSString* providerId;
@property(copy, nonatomic) NSString* description;
@property(assign, nonatomic) int count;
+ (id)rating;
+ (id)ratingWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

