/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSArray, NSURL, SALocalSearchRating, NSNumber, NSDictionary;

@interface SALocalSearchBusiness : AceObject <SAAceSerializable> {
}
@property(assign, nonatomic) int totalNumberOfReviews;
@property(retain, nonatomic) SALocalSearchRating* rating;
@property(copy, nonatomic) NSURL* photo;
@property(copy, nonatomic) NSArray* phoneNumbers;
@property(copy, nonatomic) NSString* openingHours;
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSString* extSessionGuid;
@property(copy, nonatomic) NSArray* categories;
@property(copy, nonatomic) NSURL* businessUrl;
@property(copy, nonatomic) NSDictionary* businessIds;
@property(retain, nonatomic) NSNumber* businessId;
+ (id)business;
+ (id)businessWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

