/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class SALocalSearchRating, NSURL, NSString;

@interface SALocalSearchReview : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSURL* url;
@property(copy, nonatomic) NSString* type;
@property(copy, nonatomic) NSURL* reviewerUrl;
@property(copy, nonatomic) NSString* reviewerName;
@property(retain, nonatomic) SALocalSearchRating* rating;
@property(copy, nonatomic) NSString* publication;
@property(copy, nonatomic) NSString* provider;
@property(copy, nonatomic) NSString* fullReview;
@property(copy, nonatomic) NSString* excerpt;
+ (id)reviewWithDictionary:(id)dictionary context:(id)context;
+ (id)review;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

