/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAUISnippet.h"

@class NSArray, SALocation, NSNumber;

@interface SALocalSearchMapItemSnippet : SAUISnippet {
}
@property(retain, nonatomic) NSNumber* userCurrentLocation;
@property(retain, nonatomic) SALocation* searchRegionCenter;
@property(retain, nonatomic) NSNumber* regionOfInterestRadiusInMiles;
@property(copy, nonatomic) NSArray* providerCommand;
@property(copy, nonatomic) NSArray* items;
+ (id)mapItemSnippet;
+ (id)mapItemSnippetWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

