/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSArray, NSString;

@interface SAMPSearchConstraint : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSArray* searchProperties;
@property(copy, nonatomic) NSString* query;
+ (id)searchConstraint;
+ (id)searchConstraintWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

