/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, NSString, NSArray;

@interface SAMPSearch : SABaseClientBoundCommand {
}
@property(assign, nonatomic) BOOL strict;
@property(copy, nonatomic) NSString* searchValue;
@property(copy, nonatomic) NSArray* searchTypes;
@property(copy, nonatomic) NSArray* searchProperties;
@property(assign, nonatomic) int maxResults;
@property(copy, nonatomic) NSArray* constraints;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

