/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAMPCollection.h"


@interface SAMPPlaylist : SAMPCollection {
}
+ (id)playlistWithDictionary:(id)dictionary context:(id)context;
+ (id)playlist;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

