/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAMPMediaEntity.h"

@class NSString;

@interface SAMPMediaItem : SAMPMediaEntity {
}
@property(assign, nonatomic) int trackNumber;
@property(copy, nonatomic) NSString* sortArtist;
@property(copy, nonatomic) NSString* sortAlbum;
@property(assign, nonatomic) int rating;
@property(assign, nonatomic) int playCount;
@property(copy, nonatomic) NSString* genre;
@property(copy, nonatomic) NSString* artist;
@property(copy, nonatomic) NSString* album;
+ (id)mediaItemWithDictionary:(id)dictionary context:(id)context;
+ (id)mediaItem;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

