/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class SAPerson, NSString;

@interface SAPersonAttribute : AceObject <SAAceSerializable> {
}
@property(retain, nonatomic) SAPerson* object;
@property(copy, nonatomic) NSString* displayText;
@property(copy, nonatomic) NSString* data;
+ (id)personAttribute;
+ (id)personAttributeWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

