/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, NSString, NSDate, NSNumber;

@interface SAReminderSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* timeZoneId;
@property(copy, nonatomic) NSString* subject;
@property(copy, nonatomic) NSString* listName;
@property(copy, nonatomic) NSDate* dueBefore;
@property(copy, nonatomic) NSDate* dueAfter;
@property(retain, nonatomic) NSNumber* completionStatus;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)search;
+ (id)searchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

