/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAReminderTrigger.h"

@class NSDate, NSString, SAReminderDateTimeTriggerOffset;

@interface SAReminderDateTimeTrigger : SAReminderTrigger {
}
@property(copy, nonatomic) NSString* timeZoneId;
@property(retain, nonatomic) SAReminderDateTimeTriggerOffset* relativeTimeOffset;
@property(retain, nonatomic) SAReminderDateTimeTriggerOffset* offset;
@property(copy, nonatomic) NSDate* date;
+ (id)dateTimeTrigger;
+ (id)dateTimeTriggerWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

