/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"


@interface SAReminderTrigger : AceObject <SAAceSerializable> {
}
+ (id)triggerWithDictionary:(id)dictionary context:(id)context;
+ (id)trigger;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

