/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAReminderPayload.h"
#import "AceObject.h"

@class NSArray, NSString;

@interface SAReminderEmailPayload : AceObject <SAReminderPayload> {
}
@property(copy, nonatomic) NSString* subject;
@property(copy, nonatomic) NSArray* recipientsTo;
+ (id)emailPayload;
+ (id)emailPayloadWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

