/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SABaseCommand.h"

@class NSString, NSArray, NSNumber;

@interface SASetAssistantData : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(retain, nonatomic) NSNumber* twentyFourHourTimeDisplay;
@property(copy, nonatomic) NSString* timeZoneId;
@property(copy, nonatomic) NSString* region;
@property(copy, nonatomic) NSArray* parentalRestrictions;
@property(copy, nonatomic) NSString* osVersion;
@property(copy, nonatomic) NSArray* meCards;
@property(copy, nonatomic) NSString* lastName;
@property(copy, nonatomic) NSString* language;
@property(assign, nonatomic) BOOL handsFree;
@property(copy, nonatomic) NSString* firstName;
@property(copy, nonatomic) NSString* deviceVersion;
@property(retain, nonatomic) NSNumber* debugFlags;
@property(assign, nonatomic) BOOL censorSpeech;
@property(copy, nonatomic) NSString* anchor;
@property(copy, nonatomic) NSArray* abSources;
+ (id)setAssistantData;
+ (id)setAssistantDataWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

