/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAServerBoundCommand.h"
#import "SABaseCommand.h"

@class NSString, NSDate, NSNumber;

@interface SASetRequestOrigin : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSDate* timestamp;
@property(copy, nonatomic) NSString* status;
@property(assign, nonatomic) double speed;
@property(assign, nonatomic) double direction;
@property(copy, nonatomic) NSString* desiredAccuracy;
@property(assign, nonatomic) double altitude;
@property(retain, nonatomic) NSNumber* age;
@property(assign, nonatomic) double horizontalAccuracy;
@property(assign, nonatomic) double verticalAccuracy;
@property(assign, nonatomic) double longitude;
@property(assign, nonatomic) double latitude;
+ (id)setRequestOrigin;
+ (id)setRequestOriginWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

