/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, SAPerson, NSArray;

@interface SASmsRecipientSearch : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray* recipients;
@property(retain, nonatomic) SAPerson* recipient;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)recipientSearch;
+ (id)recipientSearchWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

