/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSArray, NSURL, NSString, SAPersonAttribute, NSDate, NSNumber;

@interface SASmsSms : SADomainObject {
}
@property(copy, nonatomic) NSString* timezoneId;
@property(copy, nonatomic) NSString* subject;
@property(copy, nonatomic) NSString* sender;
@property(copy, nonatomic) NSArray* recipients;
@property(retain, nonatomic) NSNumber* outgoing;
@property(retain, nonatomic) SAPersonAttribute* msgSender;
@property(copy, nonatomic) NSArray* msgRecipients;
@property(copy, nonatomic) NSString* message;
@property(copy, nonatomic) NSDate* dateSent;
@property(copy, nonatomic) NSURL* attachment;
+ (id)sms;
+ (id)smsWithDictionary:(id)dictionary context:(id)context;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

