/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class SASRecognition, NSString;

@interface SASSpeechRecognized : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* sessionId;
@property(retain, nonatomic) SASRecognition* recognition;
+ (id)speechRecognized;
+ (id)speechRecognizedWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

