/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSString, NSNumber;

@interface SASStartSpeech : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSString* origin;
@property(retain, nonatomic) NSNumber* noiseReductionLevel;
@property(retain, nonatomic) NSNumber* motionConfidence;
@property(copy, nonatomic) NSString* motionActivity;
@property(copy, nonatomic) NSString* headsetName;
@property(copy, nonatomic) NSString* headsetId;
@property(copy, nonatomic) NSString* headsetAddress;
@property(copy, nonatomic) NSString* dspStatus;
@property(assign, nonatomic) int codec;
@property(copy, nonatomic) NSString* audioSource;
+ (id)startSpeech;
+ (id)startSpeechWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

