/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSDate, NSString;

@interface SAStockRequest : SADomainObject {
}
@property(copy, nonatomic) NSDate* startDate;
@property(copy, nonatomic) NSString* requestType;
@property(copy, nonatomic) NSDate* endDate;
+ (id)requestWithDictionary:(id)dictionary context:(id)context;
+ (id)request;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

