/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSURL, NSString, NSArray;

@interface SAStockAdd : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* tickerSymbol;
@property(copy, nonatomic) NSArray* stocks;
@property(copy, nonatomic) NSArray* stockReferences;
@property(copy, nonatomic) NSString* companyName;
@property(copy, nonatomic) NSURL* targetAppId;
+ (id)add;
+ (id)addWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

