/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SADomainObject.h"

@class NSNumber, NSString, NSArray;

@interface SAStockObject : SADomainObject {
}
@property(copy, nonatomic) NSString* yearRange;
@property(retain, nonatomic) NSNumber* volume;
@property(retain, nonatomic) NSNumber* timeStamp;
@property(copy, nonatomic) NSString* symbol;
@property(copy, nonatomic) NSArray* stockNews;
@property(retain, nonatomic) NSNumber* status;
@property(copy, nonatomic) NSArray* requests;
@property(retain, nonatomic) NSNumber* realTimeTS;
@property(retain, nonatomic) NSNumber* realTimePrice;
@property(retain, nonatomic) NSNumber* realTimeChangePercent;
@property(retain, nonatomic) NSNumber* realTimeChange;
@property(retain, nonatomic) NSNumber* price;
@property(retain, nonatomic) NSNumber* prevClose;
@property(retain, nonatomic) NSNumber* peRatio;
@property(retain, nonatomic) NSNumber* open;
@property(copy, nonatomic) NSString* name;
@property(copy, nonatomic) NSString* marketCap;
@property(retain, nonatomic) NSNumber* low;
@property(copy, nonatomic) NSString* link;
@property(retain, nonatomic) NSNumber* high;
@property(copy, nonatomic) NSString* exchange;
@property(retain, nonatomic) NSNumber* earningsPerShare;
@property(retain, nonatomic) NSNumber* dividendYield;
@property(copy, nonatomic) NSString* displayStyle;
@property(copy, nonatomic) NSString* currency;
@property(copy, nonatomic) NSString* chartData;
@property(retain, nonatomic) NSNumber* changePercent;
@property(retain, nonatomic) NSNumber* change;
@property(retain, nonatomic) NSNumber* averageDailyVolume;
+ (id)objectWithDictionary:(id)dictionary context:(id)context;
+ (id)object;
- (void)updateUsingSet:(id)set add:(id)add remove:(id)remove;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

