/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAClientBoundCommand.h"
#import "SABaseCommand.h"

@class NSString, SASyncAnchor, NSArray;

@interface SASyncChunkDenied : SABaseCommand <SAClientBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSArray* callbacks;
@property(copy, nonatomic) NSString* refId;
@property(retain, nonatomic) SASyncAnchor* current;
@property(copy, nonatomic) NSString* reason;
@property(assign, nonatomic) int errorCode;
+ (id)chunkDenied;
+ (id)chunkDeniedWithDictionary:(id)dictionary context:(id)context;
+ (id)chunkDeniedWithErrorCode:(int)errorCode;
+ (id)chunkDeniedWithReason:(id)reason;
- (id)initWithErrorCode:(int)errorCode;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
- (id)initWithReason:(id)reason;
@end

