/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class SAUIConfirmationOptions, NSArray;

@interface SAUISnippet : SAAceView {
}
@property(copy, nonatomic) NSArray* otherOptions;
@property(retain, nonatomic) SAUIConfirmationOptions* confirmationOptions;
+ (id)snippetWithDictionary:(id)dictionary context:(id)context;
+ (id)snippet;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

