/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAUISnippetInteraction.h"

@class SADomainObject;

@interface SAUISnippetObjectInteraction : SAUISnippetInteraction {
}
@property(retain, nonatomic) SADomainObject* object;
+ (id)snippetObjectInteraction;
+ (id)snippetObjectInteractionWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

