/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSString, NSArray;

@interface SAUIButton : SAAceView {
}
@property(copy, nonatomic) NSString* text;
@property(copy, nonatomic) NSArray* commands;
+ (id)buttonWithDictionary:(id)dictionary context:(id)context;
+ (id)button;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

