/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSString, NSArray;

@interface SAUIDisambiguationList : SAAceView {
}
@property(copy, nonatomic) NSString* speakableSuffix;
@property(copy, nonatomic) NSString* speakableSelectionResponse;
@property(copy, nonatomic) NSString* speakableFinalDelimiter;
@property(copy, nonatomic) NSString* speakableDelimiter;
@property(copy, nonatomic) NSString* selectionResponse;
@property(copy, nonatomic) NSArray* items;
@property(copy, nonatomic) NSString* disambiguationKey;
+ (id)disambiguationList;
+ (id)disambiguationListWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

