/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSString, NSArray;

@interface SAUIConfirmationView : SAAceView {
}
@property(copy, nonatomic) NSString* denyText;
@property(copy, nonatomic) NSArray* denyCommands;
@property(copy, nonatomic) NSString* confirmText;
@property(copy, nonatomic) NSArray* confirmCommands;
@property(copy, nonatomic) NSString* cancelTrigger;
+ (id)confirmationView;
+ (id)confirmationViewWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

