/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSString, NSArray;
@protocol SAAceSerializable;

@interface SAUIListItem : SAAceView {
}
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* speakableSelectionResponse;
@property(copy, nonatomic) NSString* selectionText;
@property(copy, nonatomic) NSString* selectionResponse;
@property(retain, nonatomic) id<SAAceSerializable> object;
@property(copy, nonatomic) NSArray* commands;
+ (id)listItemWithDictionary:(id)dictionary context:(id)context;
+ (id)listItem;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

