/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSArray;

@interface SAUIUnlockDevice : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray* successCommands;
@property(copy, nonatomic) NSArray* failureCommands;
@property(copy, nonatomic) NSArray* cancellationCommands;
+ (id)unlockDevice;
+ (id)unlockDeviceWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

