/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSString, NSArray;

@interface SAUIAddViews : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSArray* views;
@property(assign, nonatomic) BOOL temporary;
@property(assign, nonatomic) BOOL scrollToTop;
@property(copy, nonatomic) NSString* dialogPhase;
+ (id)addViews;
+ (id)addViewsWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

