/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceView.h"

@class NSURL, NSString, NSArray;

@interface SAUIMenuItem : SAAceView {
}
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* subtitle;
@property(copy, nonatomic) NSURL* ref;
@property(copy, nonatomic) NSURL* icon;
@property(copy, nonatomic) NSArray* commands;
+ (id)menuItem;
+ (id)menuItemWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

