/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAUISnippet.h"

@class NSString;

@interface SAUIErrorSnippet : SAUISnippet {
}
@property(copy, nonatomic) NSString* message;
+ (id)errorSnippet;
+ (id)errorSnippetWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

