/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseClientBoundCommand.h"

@class NSString;
@protocol SAAceSerializable;

@interface SAUISayIt : SABaseClientBoundCommand {
}
@property(copy, nonatomic) NSString* message;
@property(retain, nonatomic) id<SAAceSerializable> context;
+ (id)sayIt;
+ (id)sayItWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (BOOL)requiresResponse;
- (id)groupIdentifier;
@end

