/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, SAWeatherWindSpeed, SAWeatherBarometricPressure, SAWeatherCondition, NSNumber;

@interface SAWeatherCurrentConditions : AceObject <SAAceSerializable> {
}
@property(retain, nonatomic) SAWeatherWindSpeed* windSpeed;
@property(copy, nonatomic) NSString* windChill;
@property(copy, nonatomic) NSString* visibility;
@property(copy, nonatomic) NSString* timeZone;
@property(copy, nonatomic) NSString* timeOfObservation;
@property(copy, nonatomic) NSString* temperature;
@property(copy, nonatomic) NSString* sunset;
@property(copy, nonatomic) NSString* sunrise;
@property(retain, nonatomic) NSNumber* percentOfMoonFaceVisible;
@property(copy, nonatomic) NSString* percentHumidity;
@property(copy, nonatomic) NSString* moonPhase;
@property(copy, nonatomic) NSString* heatIndex;
@property(copy, nonatomic) NSString* feelsLike;
@property(copy, nonatomic) NSString* dewPoint;
@property(retain, nonatomic) NSNumber* dayOfWeek;
@property(retain, nonatomic) SAWeatherCondition* condition;
@property(retain, nonatomic) SAWeatherBarometricPressure* barometricPressure;
+ (id)currentConditions;
+ (id)currentConditionsWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

