/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString, NSNumber;

@interface SAWeatherWindSpeed : AceObject <SAAceSerializable> {
}
@property(retain, nonatomic) NSNumber* windDirectionDegree;
@property(copy, nonatomic) NSString* windDirection;
@property(copy, nonatomic) NSString* value;
+ (id)windSpeedWithDictionary:(id)dictionary context:(id)context;
+ (id)windSpeed;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

