/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSURL, NSString;

@interface SAWeatherLocationAddCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSURL* weatherLocationId;
@property(copy, nonatomic) NSString* error;
+ (id)locationAddCompleted;
+ (id)locationAddCompletedWithDictionary:(id)dictionary context:(id)context;
+ (id)locationAddCompletedWithError:(id)error;
+ (id)locationAddCompletedWithWeatherLocationId:(id)weatherLocationId;
- (id)initWithWeatherLocationId:(id)weatherLocationId;
- (id)encodedClassName;
- (id)groupIdentifier;
- (id)initWithError:(id)error;
@end

