/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString;

@interface SAWeatherUnits : AceObject <SAAceSerializable> {
}
@property(copy, nonatomic) NSString* temperatureUnits;
@property(copy, nonatomic) NSString* speedUnits;
@property(copy, nonatomic) NSString* pressureUnits;
@property(copy, nonatomic) NSString* distanceUnits;
+ (id)units;
+ (id)unitsWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

