/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SABaseCommand.h"
#import "SAServerBoundCommand.h"

@class NSArray, NSString;

@interface SAWeatherLocationSearchCompleted : SABaseCommand <SAServerBoundCommand> {
}
@property(copy, nonatomic) NSString* aceId;
@property(copy, nonatomic) NSString* refId;
@property(copy, nonatomic) NSArray* weatherLocations;
+ (id)locationSearchCompleted;
+ (id)locationSearchCompletedWithDictionary:(id)dictionary context:(id)context;
+ (id)locationSearchCompletedWithWeatherLocations:(id)weatherLocations;
- (id)initWithWeatherLocations:(id)weatherLocations;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

