/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class SAWeatherCondition, NSNumber;

@interface SAWeatherForecast : AceObject <SAAceSerializable> {
}
@property(retain, nonatomic) NSNumber* timeIndex;
@property(retain, nonatomic) NSNumber* isUserRequested;
@property(retain, nonatomic) SAWeatherCondition* condition;
@property(retain, nonatomic) NSNumber* chanceOfPrecipitation;
+ (id)forecast;
+ (id)forecastWithDictionary:(id)dictionary context:(id)context;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

