/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
 */

#import "SAAceSerializable.h"
#import "AceObject.h"

@class NSString;

@interface SAWeatherCondition : AceObject <SAAceSerializable> {
}
@property(assign, nonatomic) int conditionCodeIndex;
@property(copy, nonatomic) NSString* conditionCode;
+ (id)conditionWithDictionary:(id)dictionary context:(id)context;
+ (id)condition;
- (id)encodedClassName;
- (id)groupIdentifier;
@end

